# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from foundations_hw2/EulerAnglesPair.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import foundations_hw2.msg

class EulerAnglesPair(genpy.Message):
  _md5sum = "2a491fe66d9bbc50eb04b894ec3d243d"
  _type = "foundations_hw2/EulerAnglesPair"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """EulerAngles a
EulerAngles b

================================================================================
MSG: foundations_hw2/EulerAngles
float64 phi
float64 theta
float64 psi
"""
  __slots__ = ['a','b']
  _slot_types = ['foundations_hw2/EulerAngles','foundations_hw2/EulerAngles']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       a,b

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(EulerAnglesPair, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.a is None:
        self.a = foundations_hw2.msg.EulerAngles()
      if self.b is None:
        self.b = foundations_hw2.msg.EulerAngles()
    else:
      self.a = foundations_hw2.msg.EulerAngles()
      self.b = foundations_hw2.msg.EulerAngles()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.a.phi, _x.a.theta, _x.a.psi, _x.b.phi, _x.b.theta, _x.b.psi))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.a is None:
        self.a = foundations_hw2.msg.EulerAngles()
      if self.b is None:
        self.b = foundations_hw2.msg.EulerAngles()
      end = 0
      _x = self
      start = end
      end += 48
      (_x.a.phi, _x.a.theta, _x.a.psi, _x.b.phi, _x.b.theta, _x.b.psi,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.a.phi, _x.a.theta, _x.a.psi, _x.b.phi, _x.b.theta, _x.b.psi))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.a is None:
        self.a = foundations_hw2.msg.EulerAngles()
      if self.b is None:
        self.b = foundations_hw2.msg.EulerAngles()
      end = 0
      _x = self
      start = end
      end += 48
      (_x.a.phi, _x.a.theta, _x.a.psi, _x.b.phi, _x.b.theta, _x.b.psi,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6d = None
def _get_struct_6d():
    global _struct_6d
    if _struct_6d is None:
        _struct_6d = struct.Struct("<6d")
    return _struct_6d
