// Generated by gencpp from file foundations_hw2/EulerAngles.msg
// DO NOT EDIT!


#ifndef FOUNDATIONS_HW2_MESSAGE_EULERANGLES_H
#define FOUNDATIONS_HW2_MESSAGE_EULERANGLES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace foundations_hw2
{
template <class ContainerAllocator>
struct EulerAngles_
{
  typedef EulerAngles_<ContainerAllocator> Type;

  EulerAngles_()
    : phi(0.0)
    , theta(0.0)
    , psi(0.0)  {
    }
  EulerAngles_(const ContainerAllocator& _alloc)
    : phi(0.0)
    , theta(0.0)
    , psi(0.0)  {
  (void)_alloc;
    }



   typedef double _phi_type;
  _phi_type phi;

   typedef double _theta_type;
  _theta_type theta;

   typedef double _psi_type;
  _psi_type psi;




  typedef boost::shared_ptr< ::foundations_hw2::EulerAngles_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::foundations_hw2::EulerAngles_<ContainerAllocator> const> ConstPtr;

}; // struct EulerAngles_

typedef ::foundations_hw2::EulerAngles_<std::allocator<void> > EulerAngles;

typedef boost::shared_ptr< ::foundations_hw2::EulerAngles > EulerAnglesPtr;
typedef boost::shared_ptr< ::foundations_hw2::EulerAngles const> EulerAnglesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::foundations_hw2::EulerAngles_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::foundations_hw2::EulerAngles_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace foundations_hw2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/lunar/share/std_msgs/cmake/../msg'], 'foundations_hw2': ['/home/cs4750/catkin/src/foundations_hw2/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::foundations_hw2::EulerAngles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::foundations_hw2::EulerAngles_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::foundations_hw2::EulerAngles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::foundations_hw2::EulerAngles_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::foundations_hw2::EulerAngles_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::foundations_hw2::EulerAngles_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::foundations_hw2::EulerAngles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6de4259b4fd46914832c00602a20f670";
  }

  static const char* value(const ::foundations_hw2::EulerAngles_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6de4259b4fd46914ULL;
  static const uint64_t static_value2 = 0x832c00602a20f670ULL;
};

template<class ContainerAllocator>
struct DataType< ::foundations_hw2::EulerAngles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "foundations_hw2/EulerAngles";
  }

  static const char* value(const ::foundations_hw2::EulerAngles_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::foundations_hw2::EulerAngles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 phi\n\
float64 theta\n\
float64 psi\n\
";
  }

  static const char* value(const ::foundations_hw2::EulerAngles_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::foundations_hw2::EulerAngles_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.phi);
      stream.next(m.theta);
      stream.next(m.psi);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EulerAngles_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::foundations_hw2::EulerAngles_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::foundations_hw2::EulerAngles_<ContainerAllocator>& v)
  {
    s << indent << "phi: ";
    Printer<double>::stream(s, indent + "  ", v.phi);
    s << indent << "theta: ";
    Printer<double>::stream(s, indent + "  ", v.theta);
    s << indent << "psi: ";
    Printer<double>::stream(s, indent + "  ", v.psi);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FOUNDATIONS_HW2_MESSAGE_EULERANGLES_H
