// Generated by gencpp from file foundations_hw2/InterpolateRequest.msg
// DO NOT EDIT!


#ifndef FOUNDATIONS_HW2_MESSAGE_INTERPOLATEREQUEST_H
#define FOUNDATIONS_HW2_MESSAGE_INTERPOLATEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace foundations_hw2
{
template <class ContainerAllocator>
struct InterpolateRequest_
{
  typedef InterpolateRequest_<ContainerAllocator> Type;

  InterpolateRequest_()
    {
    }
  InterpolateRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }






  typedef boost::shared_ptr< ::foundations_hw2::InterpolateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::foundations_hw2::InterpolateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct InterpolateRequest_

typedef ::foundations_hw2::InterpolateRequest_<std::allocator<void> > InterpolateRequest;

typedef boost::shared_ptr< ::foundations_hw2::InterpolateRequest > InterpolateRequestPtr;
typedef boost::shared_ptr< ::foundations_hw2::InterpolateRequest const> InterpolateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::foundations_hw2::InterpolateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::foundations_hw2::InterpolateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace foundations_hw2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/lunar/share/std_msgs/cmake/../msg'], 'foundations_hw2': ['/home/cs4750/catkin/src/foundations_hw2/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::foundations_hw2::InterpolateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::foundations_hw2::InterpolateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::foundations_hw2::InterpolateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::foundations_hw2::InterpolateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::foundations_hw2::InterpolateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::foundations_hw2::InterpolateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::foundations_hw2::InterpolateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::foundations_hw2::InterpolateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::foundations_hw2::InterpolateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "foundations_hw2/InterpolateRequest";
  }

  static const char* value(const ::foundations_hw2::InterpolateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::foundations_hw2::InterpolateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::foundations_hw2::InterpolateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::foundations_hw2::InterpolateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InterpolateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::foundations_hw2::InterpolateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::foundations_hw2::InterpolateRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // FOUNDATIONS_HW2_MESSAGE_INTERPOLATEREQUEST_H
