// Generated by gencpp from file hw2/IK.msg
// DO NOT EDIT!


#ifndef HW2_MESSAGE_IK_H
#define HW2_MESSAGE_IK_H

#include <ros/service_traits.h>


#include <hw2/IKRequest.h>
#include <hw2/IKResponse.h>


namespace hw2
{

struct IK
{

typedef IKRequest Request;
typedef IKResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct IK
} // namespace hw2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hw2::IK > {
  static const char* value()
  {
    return "1de241a877ec50f4a1867b435486ffb2";
  }

  static const char* value(const ::hw2::IK&) { return value(); }
};

template<>
struct DataType< ::hw2::IK > {
  static const char* value()
  {
    return "hw2/IK";
  }

  static const char* value(const ::hw2::IK&) { return value(); }
};


// service_traits::MD5Sum< ::hw2::IKRequest> should match 
// service_traits::MD5Sum< ::hw2::IK > 
template<>
struct MD5Sum< ::hw2::IKRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hw2::IK >::value();
  }
  static const char* value(const ::hw2::IKRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hw2::IKRequest> should match 
// service_traits::DataType< ::hw2::IK > 
template<>
struct DataType< ::hw2::IKRequest>
{
  static const char* value()
  {
    return DataType< ::hw2::IK >::value();
  }
  static const char* value(const ::hw2::IKRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hw2::IKResponse> should match 
// service_traits::MD5Sum< ::hw2::IK > 
template<>
struct MD5Sum< ::hw2::IKResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hw2::IK >::value();
  }
  static const char* value(const ::hw2::IKResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hw2::IKResponse> should match 
// service_traits::DataType< ::hw2::IK > 
template<>
struct DataType< ::hw2::IKResponse>
{
  static const char* value()
  {
    return DataType< ::hw2::IK >::value();
  }
  static const char* value(const ::hw2::IKResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HW2_MESSAGE_IK_H
