// Generated by gencpp from file hw2/p1bRequest.msg
// DO NOT EDIT!


#ifndef HW2_MESSAGE_P1BREQUEST_H
#define HW2_MESSAGE_P1BREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <foundations_hw2/JointAngles.h>

namespace hw2
{
template <class ContainerAllocator>
struct p1bRequest_
{
  typedef p1bRequest_<ContainerAllocator> Type;

  p1bRequest_()
    : angle()  {
    }
  p1bRequest_(const ContainerAllocator& _alloc)
    : angle(_alloc)  {
  (void)_alloc;
    }



   typedef  ::foundations_hw2::JointAngles_<ContainerAllocator>  _angle_type;
  _angle_type angle;




  typedef boost::shared_ptr< ::hw2::p1bRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hw2::p1bRequest_<ContainerAllocator> const> ConstPtr;

}; // struct p1bRequest_

typedef ::hw2::p1bRequest_<std::allocator<void> > p1bRequest;

typedef boost::shared_ptr< ::hw2::p1bRequest > p1bRequestPtr;
typedef boost::shared_ptr< ::hw2::p1bRequest const> p1bRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hw2::p1bRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hw2::p1bRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hw2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/lunar/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/lunar/share/std_msgs/cmake/../msg'], 'foundations_hw2': ['/home/cs4750/catkin/src/foundations_hw2/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hw2::p1bRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hw2::p1bRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hw2::p1bRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hw2::p1bRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hw2::p1bRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hw2::p1bRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hw2::p1bRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b4a945124d95d3b8be9721d07efdaf3b";
  }

  static const char* value(const ::hw2::p1bRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb4a945124d95d3b8ULL;
  static const uint64_t static_value2 = 0xbe9721d07efdaf3bULL;
};

template<class ContainerAllocator>
struct DataType< ::hw2::p1bRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hw2/p1bRequest";
  }

  static const char* value(const ::hw2::p1bRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hw2::p1bRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "foundations_hw2/JointAngles angle\n\
\n\
================================================================================\n\
MSG: foundations_hw2/JointAngles\n\
float64[5] angles\n\
";
  }

  static const char* value(const ::hw2::p1bRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hw2::p1bRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct p1bRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hw2::p1bRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hw2::p1bRequest_<ContainerAllocator>& v)
  {
    s << indent << "angle: ";
    s << std::endl;
    Printer< ::foundations_hw2::JointAngles_<ContainerAllocator> >::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HW2_MESSAGE_P1BREQUEST_H
