// Generated by gencpp from file hw2/p2b.msg
// DO NOT EDIT!


#ifndef HW2_MESSAGE_P2B_H
#define HW2_MESSAGE_P2B_H

#include <ros/service_traits.h>


#include <hw2/p2bRequest.h>
#include <hw2/p2bResponse.h>


namespace hw2
{

struct p2b
{

typedef p2bRequest Request;
typedef p2bResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct p2b
} // namespace hw2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hw2::p2b > {
  static const char* value()
  {
    return "bd9ef8a2f54d1aab08300de4419aaf70";
  }

  static const char* value(const ::hw2::p2b&) { return value(); }
};

template<>
struct DataType< ::hw2::p2b > {
  static const char* value()
  {
    return "hw2/p2b";
  }

  static const char* value(const ::hw2::p2b&) { return value(); }
};


// service_traits::MD5Sum< ::hw2::p2bRequest> should match 
// service_traits::MD5Sum< ::hw2::p2b > 
template<>
struct MD5Sum< ::hw2::p2bRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hw2::p2b >::value();
  }
  static const char* value(const ::hw2::p2bRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hw2::p2bRequest> should match 
// service_traits::DataType< ::hw2::p2b > 
template<>
struct DataType< ::hw2::p2bRequest>
{
  static const char* value()
  {
    return DataType< ::hw2::p2b >::value();
  }
  static const char* value(const ::hw2::p2bRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hw2::p2bResponse> should match 
// service_traits::MD5Sum< ::hw2::p2b > 
template<>
struct MD5Sum< ::hw2::p2bResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hw2::p2b >::value();
  }
  static const char* value(const ::hw2::p2bResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hw2::p2bResponse> should match 
// service_traits::DataType< ::hw2::p2b > 
template<>
struct DataType< ::hw2::p2bResponse>
{
  static const char* value()
  {
    return DataType< ::hw2::p2b >::value();
  }
  static const char* value(const ::hw2::p2bResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HW2_MESSAGE_P2B_H
