// Generated by gencpp from file foundations_hw1/EscapeResponse.msg
// DO NOT EDIT!


#ifndef FOUNDATIONS_HW1_MESSAGE_ESCAPERESPONSE_H
#define FOUNDATIONS_HW1_MESSAGE_ESCAPERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace foundations_hw1
{
template <class ContainerAllocator>
struct EscapeResponse_
{
  typedef EscapeResponse_<ContainerAllocator> Type;

  EscapeResponse_()
    : goal()  {
    }
  EscapeResponse_(const ContainerAllocator& _alloc)
    : goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _goal_type;
  _goal_type goal;




  typedef boost::shared_ptr< ::foundations_hw1::EscapeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::foundations_hw1::EscapeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct EscapeResponse_

typedef ::foundations_hw1::EscapeResponse_<std::allocator<void> > EscapeResponse;

typedef boost::shared_ptr< ::foundations_hw1::EscapeResponse > EscapeResponsePtr;
typedef boost::shared_ptr< ::foundations_hw1::EscapeResponse const> EscapeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::foundations_hw1::EscapeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::foundations_hw1::EscapeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace foundations_hw1

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/lunar/share/geometry_msgs/cmake/../msg'], 'turtlesim': ['/opt/ros/lunar/share/turtlesim/cmake/../msg'], 'std_msgs': ['/opt/ros/lunar/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::foundations_hw1::EscapeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::foundations_hw1::EscapeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::foundations_hw1::EscapeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::foundations_hw1::EscapeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::foundations_hw1::EscapeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::foundations_hw1::EscapeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::foundations_hw1::EscapeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8ad3bd0e46ff6777ce7cd2fdd945cb9e";
  }

  static const char* value(const ::foundations_hw1::EscapeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8ad3bd0e46ff6777ULL;
  static const uint64_t static_value2 = 0xce7cd2fdd945cb9eULL;
};

template<class ContainerAllocator>
struct DataType< ::foundations_hw1::EscapeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "foundations_hw1/EscapeResponse";
  }

  static const char* value(const ::foundations_hw1::EscapeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::foundations_hw1::EscapeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point goal\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::foundations_hw1::EscapeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::foundations_hw1::EscapeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EscapeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::foundations_hw1::EscapeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::foundations_hw1::EscapeResponse_<ContainerAllocator>& v)
  {
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FOUNDATIONS_HW1_MESSAGE_ESCAPERESPONSE_H
