// Generated by gencpp from file foundations_hw1/EscapeRequest.msg
// DO NOT EDIT!


#ifndef FOUNDATIONS_HW1_MESSAGE_ESCAPEREQUEST_H
#define FOUNDATIONS_HW1_MESSAGE_ESCAPEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <turtlesim/Pose.h>

namespace foundations_hw1
{
template <class ContainerAllocator>
struct EscapeRequest_
{
  typedef EscapeRequest_<ContainerAllocator> Type;

  EscapeRequest_()
    : pose()
    , name()  {
    }
  EscapeRequest_(const ContainerAllocator& _alloc)
    : pose(_alloc)
    , name(_alloc)  {
  (void)_alloc;
    }



   typedef  ::turtlesim::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;




  typedef boost::shared_ptr< ::foundations_hw1::EscapeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::foundations_hw1::EscapeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct EscapeRequest_

typedef ::foundations_hw1::EscapeRequest_<std::allocator<void> > EscapeRequest;

typedef boost::shared_ptr< ::foundations_hw1::EscapeRequest > EscapeRequestPtr;
typedef boost::shared_ptr< ::foundations_hw1::EscapeRequest const> EscapeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::foundations_hw1::EscapeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::foundations_hw1::EscapeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace foundations_hw1

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/lunar/share/geometry_msgs/cmake/../msg'], 'turtlesim': ['/opt/ros/lunar/share/turtlesim/cmake/../msg'], 'std_msgs': ['/opt/ros/lunar/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::foundations_hw1::EscapeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::foundations_hw1::EscapeRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::foundations_hw1::EscapeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::foundations_hw1::EscapeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::foundations_hw1::EscapeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::foundations_hw1::EscapeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::foundations_hw1::EscapeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ce0c71b59408620faa9fbfc37c9cad95";
  }

  static const char* value(const ::foundations_hw1::EscapeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xce0c71b59408620fULL;
  static const uint64_t static_value2 = 0xaa9fbfc37c9cad95ULL;
};

template<class ContainerAllocator>
struct DataType< ::foundations_hw1::EscapeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "foundations_hw1/EscapeRequest";
  }

  static const char* value(const ::foundations_hw1::EscapeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::foundations_hw1::EscapeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlesim/Pose pose\n\
string name\n\
\n\
================================================================================\n\
MSG: turtlesim/Pose\n\
float32 x\n\
float32 y\n\
float32 theta\n\
\n\
float32 linear_velocity\n\
float32 angular_velocity\n\
";
  }

  static const char* value(const ::foundations_hw1::EscapeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::foundations_hw1::EscapeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EscapeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::foundations_hw1::EscapeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::foundations_hw1::EscapeRequest_<ContainerAllocator>& v)
  {
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::turtlesim::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FOUNDATIONS_HW1_MESSAGE_ESCAPEREQUEST_H
