// Generated by gencpp from file foundations_hw1/Escape.msg
// DO NOT EDIT!


#ifndef FOUNDATIONS_HW1_MESSAGE_ESCAPE_H
#define FOUNDATIONS_HW1_MESSAGE_ESCAPE_H

#include <ros/service_traits.h>


#include <foundations_hw1/EscapeRequest.h>
#include <foundations_hw1/EscapeResponse.h>


namespace foundations_hw1
{

struct Escape
{

typedef EscapeRequest Request;
typedef EscapeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Escape
} // namespace foundations_hw1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::foundations_hw1::Escape > {
  static const char* value()
  {
    return "89ed0fab02445014d3380c75507816b5";
  }

  static const char* value(const ::foundations_hw1::Escape&) { return value(); }
};

template<>
struct DataType< ::foundations_hw1::Escape > {
  static const char* value()
  {
    return "foundations_hw1/Escape";
  }

  static const char* value(const ::foundations_hw1::Escape&) { return value(); }
};


// service_traits::MD5Sum< ::foundations_hw1::EscapeRequest> should match 
// service_traits::MD5Sum< ::foundations_hw1::Escape > 
template<>
struct MD5Sum< ::foundations_hw1::EscapeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::foundations_hw1::Escape >::value();
  }
  static const char* value(const ::foundations_hw1::EscapeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::foundations_hw1::EscapeRequest> should match 
// service_traits::DataType< ::foundations_hw1::Escape > 
template<>
struct DataType< ::foundations_hw1::EscapeRequest>
{
  static const char* value()
  {
    return DataType< ::foundations_hw1::Escape >::value();
  }
  static const char* value(const ::foundations_hw1::EscapeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::foundations_hw1::EscapeResponse> should match 
// service_traits::MD5Sum< ::foundations_hw1::Escape > 
template<>
struct MD5Sum< ::foundations_hw1::EscapeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::foundations_hw1::Escape >::value();
  }
  static const char* value(const ::foundations_hw1::EscapeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::foundations_hw1::EscapeResponse> should match 
// service_traits::DataType< ::foundations_hw1::Escape > 
template<>
struct DataType< ::foundations_hw1::EscapeResponse>
{
  static const char* value()
  {
    return DataType< ::foundations_hw1::Escape >::value();
  }
  static const char* value(const ::foundations_hw1::EscapeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FOUNDATIONS_HW1_MESSAGE_ESCAPE_H
