// Generated by gencpp from file foundations_hw1/Reward.msg
// DO NOT EDIT!


#ifndef FOUNDATIONS_HW1_MESSAGE_REWARD_H
#define FOUNDATIONS_HW1_MESSAGE_REWARD_H

#include <ros/service_traits.h>


#include <foundations_hw1/RewardRequest.h>
#include <foundations_hw1/RewardResponse.h>


namespace foundations_hw1
{

struct Reward
{

typedef RewardRequest Request;
typedef RewardResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Reward
} // namespace foundations_hw1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::foundations_hw1::Reward > {
  static const char* value()
  {
    return "e4b5d32ae3ca1cd1c0a07d0712fcdd49";
  }

  static const char* value(const ::foundations_hw1::Reward&) { return value(); }
};

template<>
struct DataType< ::foundations_hw1::Reward > {
  static const char* value()
  {
    return "foundations_hw1/Reward";
  }

  static const char* value(const ::foundations_hw1::Reward&) { return value(); }
};


// service_traits::MD5Sum< ::foundations_hw1::RewardRequest> should match 
// service_traits::MD5Sum< ::foundations_hw1::Reward > 
template<>
struct MD5Sum< ::foundations_hw1::RewardRequest>
{
  static const char* value()
  {
    return MD5Sum< ::foundations_hw1::Reward >::value();
  }
  static const char* value(const ::foundations_hw1::RewardRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::foundations_hw1::RewardRequest> should match 
// service_traits::DataType< ::foundations_hw1::Reward > 
template<>
struct DataType< ::foundations_hw1::RewardRequest>
{
  static const char* value()
  {
    return DataType< ::foundations_hw1::Reward >::value();
  }
  static const char* value(const ::foundations_hw1::RewardRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::foundations_hw1::RewardResponse> should match 
// service_traits::MD5Sum< ::foundations_hw1::Reward > 
template<>
struct MD5Sum< ::foundations_hw1::RewardResponse>
{
  static const char* value()
  {
    return MD5Sum< ::foundations_hw1::Reward >::value();
  }
  static const char* value(const ::foundations_hw1::RewardResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::foundations_hw1::RewardResponse> should match 
// service_traits::DataType< ::foundations_hw1::Reward > 
template<>
struct DataType< ::foundations_hw1::RewardResponse>
{
  static const char* value()
  {
    return DataType< ::foundations_hw1::Reward >::value();
  }
  static const char* value(const ::foundations_hw1::RewardResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FOUNDATIONS_HW1_MESSAGE_REWARD_H
